# Generated by Django 2.2.6 on 2019-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_entry_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
