# Generated by Django 2.2.6 on 2019-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_compute_some_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.FloatField(),
        ),
    ]
